# Usa uma imagem do Node.js LTS
FROM node:22.14.0

# Define o diretório de trabalho
WORKDIR /app

# Copia o restante dos arquivos
COPY package*.json ./
RUN npm install

# Copia os arquivos de dependências e instala
COPY . .

# Instala nodemon para recarregar código automaticamente
RUN npm install -g nodemon

EXPOSE 3001

CMD ["npm", "run", "start:dev"]